name: 'Synchronize two drupal instances'
description: 'Assumes robo.yml is configured on the target server and eaudeweb/heavy-lifter on the source server'
inputs:
  target_ssh_user:
    description: 'Destination SSH user account'
    required: true
  target_ssh_host:
    description: 'Destination SSH host server'
    required: true
  target_ssh_key:
    description: 'Destination SSH private key'
    required: true
  target_project_dir:
    description: 'Absolute path where the project root is configured (where live symlink exists)'
    required: true
  sync_db:
    description: 'Sync SQL database'
    default: true
  sync_files:
    description: 'Sync "files" archive'
    default: false

runs:
  using: "composite"
  steps:
    - name: 'Configure SSH'
      run: |
        mkdir -p ~/.ssh/
        echo "$SSH_KEY" > ~/.ssh/server.key
        chmod 600 ~/.ssh/server.key
        cat > ~/.ssh/config <<END
        Host server
          HostName $SSH_HOST
          User $SSH_USER
          IdentityFile ~/.ssh/server.key
          StrictHostKeyChecking no
        END
      env:
        SSH_USER: ${{ inputs.target_ssh_user }}
        SSH_HOST: ${{ inputs.target_ssh_host }}
        SSH_KEY: ${{ inputs.target_ssh_key }}
      shell: bash

    - name: 'Synchronize database from source to target'
      if:  ${{ inputs.sync_db == 'true' }}
      run: |
        ssh server 'cd ${{ inputs.target_project_dir }} && ./vendor/bin/robo sql:sync'
      shell: bash
    - name: 'Synchronize files archive'
      if:  ${{ inputs.sync_files == 'true' }}
      run: |
        ssh server 'cd ${{ inputs.target_project_dir }} && ./vendor/bin/robo files:sync'
      shell: bash
